CREATE TABLE CUSTOMER (
CUSTOMER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(150),
LAST_NAME VARCHAR(150),
PHONE_NUM VARCHAR(150),
AGE INTEGER
);

CREATE TABLE TICKETS (
TICKET_ID INTEGER PRIMARY KEY,
SEAT_NUMBER INT,
ROW_ VARCHAR(150),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (ITEM_ID) REFERENCES CONCESSIONS(ITEM_ID),
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID)
);

CREATE TABLE CONCESSIONS (
ITEM_ID INT PRIMARY KEY,
PRICE NUMERIC(5,2),
DESCRIPTION VARCHAR(150)
);

CREATE TABLE MOVIES (
MOVIE_ID INT PRIMARY KEY,
TITLE VARCHAR(150),
MAIN_CHARACTER VARCHAR(150),
DURATION INT,
RATING VARCHAR(150)
);

select * from CUSTOMER;
select * from TICKETS;
select * from CONCESSIONS;
select * from MOVIES;